/* Generated by Yosys 0.56+105 (git sha1 1dbf2df98, g++ 12.2.0-14+deb12u1 -fprofile-arcs -ftest-coverage -fPIC -O3) */

module ModuleBasic(a, b, out_a, out_b);
  input a;
  wire a;
  input [31:0] b;
  wire [31:0] b;
  output out_a;
  wire out_a;
  output [31:0] out_b;
  wire [31:0] out_b;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire c;
  wire [31:0] d;
  assign out_b[1] = ~b[1];
  assign out_b[2] = ~(b[2] ^ b[1]);
  assign _033_ = ~(b[2] | b[1]);
  assign out_b[3] = _033_ ^ b[3];
  assign _034_ = b[3] | b[2];
  assign _035_ = b[1] & ~(_034_);
  assign _036_ = _035_ | _034_;
  assign out_b[4] = ~(_036_ ^ b[4]);
  assign _037_ = _036_ | b[4];
  assign out_b[5] = _037_ ^ b[5];
  assign _038_ = ~(b[5] & b[4]);
  assign _039_ = b[4] | ~(b[5]);
  assign _040_ = _036_ & ~(_039_);
  assign _041_ = _038_ & ~(_040_);
  assign out_b[6] = ~(_041_ ^ b[6]);
  assign _042_ = b[6] & ~(_041_);
  assign out_b[7] = _042_ ^ b[7];
  assign _043_ = ~(b[7] & b[6]);
  assign _044_ = _043_ | _038_;
  assign _045_ = _043_ | _039_;
  assign _046_ = _036_ & ~(_045_);
  assign _047_ = _044_ & ~(_046_);
  assign out_b[8] = ~(_047_ ^ b[8]);
  assign _048_ = b[8] & ~(_047_);
  assign out_b[9] = _048_ ^ b[9];
  assign _049_ = ~(b[9] & b[8]);
  assign _050_ = _049_ | _047_;
  assign out_b[10] = ~(_050_ ^ b[10]);
  assign _051_ = b[10] & ~(_050_);
  assign out_b[11] = _051_ ^ b[11];
  assign _052_ = ~(b[11] & b[10]);
  assign _053_ = _052_ | _049_;
  assign _054_ = ~(_053_ | _047_);
  assign out_b[12] = _054_ ^ b[12];
  assign _055_ = _054_ & b[12];
  assign out_b[13] = _055_ ^ b[13];
  assign _000_ = ~(b[13] & b[12]);
  assign _001_ = _000_ | ~(_054_);
  assign out_b[14] = ~(_001_ ^ b[14]);
  assign _002_ = b[14] & ~(_001_);
  assign out_b[15] = _002_ ^ b[15];
  assign _003_ = ~(b[15] & b[14]);
  assign _004_ = _003_ | _000_;
  assign _005_ = _004_ | _053_;
  assign _006_ = _005_ | _047_;
  assign out_b[16] = ~(_006_ ^ b[16]);
  assign _007_ = b[16] & ~(_006_);
  assign out_b[17] = _007_ ^ b[17];
  assign _008_ = ~(b[17] & b[16]);
  assign _009_ = _008_ | _006_;
  assign out_b[18] = ~(_009_ ^ b[18]);
  assign _010_ = b[18] & ~(_009_);
  assign out_b[19] = _010_ ^ b[19];
  assign _011_ = ~(b[19] & b[18]);
  assign _012_ = _011_ | _008_;
  assign _013_ = _012_ | _006_;
  assign out_b[20] = ~(_013_ ^ b[20]);
  assign _014_ = b[20] & ~(_013_);
  assign out_b[21] = _014_ ^ b[21];
  assign _015_ = ~(b[21] & b[20]);
  assign _016_ = _015_ | _013_;
  assign out_b[22] = ~(_016_ ^ b[22]);
  assign _017_ = b[22] & ~(_016_);
  assign out_b[23] = _017_ ^ b[23];
  assign _018_ = ~(b[23] & b[22]);
  assign _019_ = _018_ | _015_;
  assign _020_ = _019_ | _012_;
  assign _021_ = _020_ | _006_;
  assign out_b[24] = ~(_021_ ^ b[24]);
  assign _022_ = b[24] & ~(_021_);
  assign out_b[25] = _022_ ^ b[25];
  assign _023_ = ~(b[25] & b[24]);
  assign _024_ = _023_ | _021_;
  assign out_b[26] = ~(_024_ ^ b[26]);
  assign _025_ = b[26] & ~(_024_);
  assign out_b[27] = _025_ ^ b[27];
  assign _026_ = ~(b[27] & b[26]);
  assign _027_ = _026_ | _023_;
  assign _028_ = _027_ | _021_;
  assign out_b[28] = ~(_028_ ^ b[28]);
  assign _029_ = b[28] & ~(_028_);
  assign out_b[29] = _029_ ^ b[29];
  assign _030_ = ~(b[29] & b[28]);
  assign _031_ = _030_ | _028_;
  assign out_b[30] = ~(_031_ ^ b[30]);
  assign _032_ = b[30] & ~(_031_);
  assign out_b[31] = _032_ ^ b[31];
  assign c = b[0];
  assign d = b;
  assign out_a = a;
  assign out_b[0] = b[0];
endmodule

module interface_module(clk, in_bus, inj_data_in_1755538390179_979, inj_sel_in_1755538390179_688, out_bus, rst_n, inj_data_out_1755538390179_328, \out_bus.valid , \in_bus.ready , \in_bus.valid , \in_bus.data , \out_bus.ready , \out_bus.data );
  input clk;
  wire clk;
  inout in_bus;
  wire in_bus;
  input [3:0] inj_data_in_1755538390179_979;
  wire [3:0] inj_data_in_1755538390179_979;
  input [31:0] inj_sel_in_1755538390179_688;
  wire [31:0] inj_sel_in_1755538390179_688;
  inout out_bus;
  wire out_bus;
  input rst_n;
  wire rst_n;
  output [7:0] inj_data_out_1755538390179_328;
  wire [7:0] inj_data_out_1755538390179_328;
  output [0:0] \out_bus.valid ;
  reg [0:0] \out_bus.valid ;
  output [0:0] \in_bus.ready ;
  wire [0:0] \in_bus.ready ;
  input [0:0] \in_bus.valid ;
  wire [0:0] \in_bus.valid ;
  input [7:0] \in_bus.data ;
  wire [7:0] \in_bus.data ;
  input [0:0] \out_bus.ready ;
  wire [0:0] \out_bus.ready ;
  output [7:0] \out_bus.data ;
  wire [7:0] \out_bus.data ;
  wire _00_;
  wire _01_;
  wire [1:0] \gen_loop[0].sub_in_ts1755538390180 ;
  wire [31:0] \gen_loop[0].temp_int_ts1755538390180 ;
  wire [1:0] \gen_loop[1].sub_in_ts1755538390180 ;
  wire [31:0] \gen_loop[1].temp_int_ts1755538390180 ;
  reg [7:0] stored_data;
  assign _00_ = ~(\out_bus.ready  & \out_bus.valid );
  assign _01_ = \in_bus.valid  | ~(_00_);
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \out_bus.valid  <= 1'h0;
    else if (_01_) \out_bus.valid  <= _00_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) stored_data[0] <= 1'h0;
    else if (\in_bus.valid ) stored_data[0] <= \in_bus.data [0];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) stored_data[1] <= 1'h0;
    else if (\in_bus.valid ) stored_data[1] <= \in_bus.data [1];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) stored_data[2] <= 1'h0;
    else if (\in_bus.valid ) stored_data[2] <= \in_bus.data [2];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) stored_data[3] <= 1'h0;
    else if (\in_bus.valid ) stored_data[3] <= \in_bus.data [3];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) stored_data[4] <= 1'h0;
    else if (\in_bus.valid ) stored_data[4] <= \in_bus.data [4];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) stored_data[5] <= 1'h0;
    else if (\in_bus.valid ) stored_data[5] <= \in_bus.data [5];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) stored_data[6] <= 1'h0;
    else if (\in_bus.valid ) stored_data[6] <= \in_bus.data [6];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) stored_data[7] <= 1'h0;
    else if (\in_bus.valid ) stored_data[7] <= \in_bus.data [7];
  ModuleBasic \gen_loop[0].m_inst  (
    .a(1'h0),
    .b({ 30'h00000000, inj_data_in_1755538390179_979[1:0] }),
    .out_b(\gen_loop[0].temp_int_ts1755538390180 )
  );
  ModuleBasic \gen_loop[1].m_inst  (
    .a(1'h0),
    .b({ 30'h00000000, inj_data_in_1755538390179_979[3:2] }),
    .out_b(\gen_loop[1].temp_int_ts1755538390180 )
  );
  assign \gen_loop[0].sub_in_ts1755538390180  = inj_data_in_1755538390179_979[1:0];
  assign \gen_loop[1].sub_in_ts1755538390180  = inj_data_in_1755538390179_979[3:2];
  assign \in_bus.ready  = 1'h1;
  assign inj_data_out_1755538390179_328 = { \gen_loop[1].temp_int_ts1755538390180 [3:0], \gen_loop[0].temp_int_ts1755538390180 [3:0] };
  assign \out_bus.data  = stored_data;
endmodule

module simple_bus();
endmodule
