[project]
name = "snippetGen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "toby", email = "toby.bro@pm.me" }
]
requires-python = ">=3.13"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
